### ISSUE TITLE
Small chapter 4 mistakes altering meaning

### ISSUE THREAD

**Issue by Antymon** [mml-book/mml-book.github.io#117]
**Describe the mistake**

lines:
2308 vectors -> values
2381 Mentioned theorem only brings up orthogonality not orthonormality 
2408 or A -> of A

equations:
4.70 should have D instead of A on the right hand side

**Location**
Please provide the 
1. version 2018-09-21
2. Chapter 4

**Comment by AnalogAldo** [comment]
_2308 vectors -> values_
Not sure I understand the issue: the sentence is about the \Sigma matrix which is a matrix of the singular values \sigma_i, it is not a matrix of singular vectors.

_2381 Mentioned theorem only brings up orthogonality not orthonormality_
Thank you, that is correct, although we can always normalise the basis to be orthonormal.

_2408 or A -> of A_

_4.70 should have D instead of A on the right hand side._ 
Thank you, Fixed.

**Comment by Antymon** [comment]
Line 2308 used to read as follows "[By convention the singular] vectors are ordered, i.e., σ 1> σ 2> σ r> 0." I understood that lower case sigmas used to represent values, and not vectors as stated in the line. If I am confusing something please feel free to ignore.

**Comment by AnalogAldo** [comment]
I have clarified this now explicitly.
