### ISSUE TITLE
Eigenvectors of symmetric matrices, Chapter 4

### ISSUE THREAD

**Issue by empet** [mml-book/mml-book.github.io#216]
It is mentioned that *The eigenvectors of symmetric matrices are always orthogonal to each other*.

1. Draft 2018-11-03
2. Chapter 4
3. Page: 105
4. line number: 2101

**Proposed solution**
*The eigenvectors of a symmetric matrix, corresponding to distinct eigenvalues, are orthogonal vectors.*

Here is an example of symmetric matrix with non-orthogonal eigenvectors:

![symm-matrix](https://user-images.githubusercontent.com/3627253/49854640-795fc580-fdf3-11e8-8994-5b7aeda68493.png)

![example-non-orth-eigv](https://user-images.githubusercontent.com/3627253/49854674-98f6ee00-fdf3-11e8-8dbb-619363dc64c3.png)

Using the Gramm-Schmidt orthogonalization method we can get from this basis, (v_1, v_2), an orthogonal basis of eigenvectors, w_1, w_2 in E_{\lambda=1}.

**Comment by AnalogAldo** [comment]
Yes, that is good point, as the defintion was not restricted in itself to n distinct eigenvalues, as we covered defective only before. We have now rephrased the theorem and added a remark to make this clear.

**Comment by mpd37** [comment]
I re-opened the issue because it is currently not addressed. But it will be fixed with the next update of Chapter 4.

**Comment by mpd37** [comment]
I found the solution:

a) for every symmetric matrix, there exists an orthogonal basis of eigenvectors (this comes straight from the spectral theorem)
b) If we have repeated eigenvalues, the basis we find may not be orthogonal yet, but we can construct one using the Gram-Schmidt process. We can do this because a linear combination of eigenvectors associated with the same eigenvalue remains an eigenvector. And Gram-Schmidt just applies linear mappings (i.e., linear combinations).

I tried to write this down for the example you gave here:

![image](https://user-images.githubusercontent.com/5500569/53203008-e11a6400-361f-11e9-8a68-6c7c4992f561.png)

**Comment by empet** [comment]
Right!!!  Eventually, adding that the  constructed orthogonal vectors in the eigenspace corresponding to a multiple eigenvalue are still orthogonal on vectors in other eigenspaces because they correspond to distinct eigenvalue. In the case of the above example $x_3$ is orthogonal to $x'_1, x_'2$ because $7\neq 1$.

**Comment by mpd37** [comment]
Yes, this is correct. But honestly, the example you gave here caused me a lot of trouble in the last days ;) 
Thanks! I really appreciate it.
