### ISSUE TITLE
Mistake example 6.2

### ISSUE THREAD

**Issue by victorBigand** [mml-book/mml-book.github.io#230]
**Describe the mistake**
In the example, i think there is errors in the indices of the sums to calculate ci (column frequencies) and rj (row frequencies)

Indeed, in the first case (but it is the same error for the second) the sum increments from one to 3 which are the row numbers but inside the sum in nij it is the column number which is increasing.

**Location**
Please provide the 
1. version 2018-11-14
2. chapter 6
3. page 180
4. example 6.2 at the beginning

**Comment by chengsoonong** [comment]
I am trying to clarify what you think the error is.

To calculate c_4, we sum n_{41} + n_{42} + n_{43}
There are 5 values of c_i

the number n_{ij}, 
i refers to the column index (of which there are 5)
j refers to the row index (of which there are 3)

Is the confusion because of the order of the presentation {ij} and not {ji}?

Or do you mean some other error that I did not understand from your report?

**Comment by victorBigand** [comment]
Yes i am confused as why write the column number first, is it something usual? I didn't read this notation anywhere

**Comment by chengsoonong** [comment]
I've added a sentence in the example to clarify n_{ij}.

It is a bit unfortunate that the column number is written as the first index, but changing it might introduce other knock on effects. We aren't really talking about matrices, but just a representation of probabilities, so "row" and "column" really just refer to random variables X and Y.

**Comment by zhouchiji** [comment]
this part of the marginal probability formula. Why divide by the total number of events N? ps the formula is (6.10)
