### ISSUE TITLE
Wrong dimension in chapter 10 line 5871

### ISSUE THREAD

**Issue by moebiuscurve** [mml-book/mml-book.github.io#242]
**Describe the mistake**
\widetilde{x}_n \in \mathbb{R}^D : the dimension should be M instead of D. \widetilde{x}_n is element of U, which has dimension M.

**Location**
1. version: Draft(2018-11-18)
2. Chapter: 10
3. page: 315
4. line number: 5871

**Proposed solution**
\widetilde{x}_n \in \mathbb{R}^D  should be \widetilde{x}_n \in \mathbb{R}^M

**Comment by mpd37** [comment]
\tilde x_n is the reconstruction in the original data space, so it's dimension is D.

**Comment by moebiuscurve** [comment]
Then shouldn't line 5869 also indicate \tilde x_n \in R^D instead of \tilde x_n \in U ?

**Comment by mpd37** [comment]
U is a subspace of R^D, i.e., vectors in U have D elements. However, to represent vectors in U we only need M basis vectors (each of them has D elements), so that dim(U) = M.

Example: [1, 0]^T spans a one-dimensional subspace of R^2. All vectors living in this subspace still have two components, but the 2nd component is always 0. 

Does this make more sense now?

**Comment by moebiuscurve** [comment]
Yep, it makes sense now
