### ISSUE TITLE
Theorem 4.25

### ISSUE THREAD

**Issue by CL-BZH** [mml-book/mml-book.github.io#343]
**Describe the mistake**
In Theorem 4.25 it is written "let B be a matrix of rank k". But equation (4.94) is for rk(B) \leq k.

**Location**
Please provide the 
1. version (bottom of page): Draft (2019-06-04)
2. Chapter: 4
3. page: 131
4. line number/equation number: Theorem 4.25

**Proposed solution**
Just write "let B ∈ Rmxn" (i.e. not mentioning its rank), 
or write "let B be a matrix of rank \leq k"
or again, write equation (4.94) with argmin_{rk(B)=k}.

**Additional context**

**Comment by mpd37** [comment]
The theorem (as it stands) should be fine because rk(B) < k - matrices incur more error than rank-k matrices B. However, it would be easier to read (also in the context of the chapter) if we go for rk(B)=k, because u_i and v_i are supposed to be basis vectors. 

Summary: Thanks for pointing this out. We'll change this into rk(B)=k in the subscript of argmin
