### ISSUE TITLE
Typography error on Section 2.3

### ISSUE THREAD

**Issue by srakrn** [mml-book/mml-book.github.io#380]
**Describe the mistake**

*[Link to the book's screenshot](https://imgur.com/a/jK6B6Xg)*

From my point of view, the notation on the row multiplication with any non-zero constant is confusing with the backslash sign.

**Location**
1. Version: Draft (2019-08-11) 
2. Chapter: 2.3.2
3. Page: 29
4. Line number: 3

**Proposed solution**

The bullet point should be changed into
```latex
Multiplication of an equation (row) with a constant $ \lambda \in \mathbb{R} - \left{ 0 \right} $
```
to clearly indicates that the set of the multiplicable constant does not include zero.

**Comment by mpd37** [comment]
The notation we use is standard notation, and \ indicates a difference in (or: complement of) sets. You can read it as "real numbers without 0". 
https://en.wikipedia.org/wiki/Complement_(set_theory)

Using a "-" would be confusing to many people because they would read it as "subtract 0 from every real number", which wouldn't do anything.

**Comment by srakrn** [comment]
Thank you!
