### ISSUE TITLE
Cumulative feedback on first view

### ISSUE THREAD

**Issue by Atcold** [mml-book/mml-book.github.io#40]
Would you mind using $\mathbb{R}$ for the blackboard R?
What about $\mathbb{I}$ for the identity matrix?
Use $\varnothing$ instead of $\emptyset$?
Also, isn't the gradient (column vector) the transposed of the Jacobian (row vector)?
What about having the differential operator d upright, and not like a variable?
Figure 5.6 uses bold upright font, instead of the italic one.
Coloured equations (like 5.189) have bad spacing when the colour is changed. Have a look at the "+" spacing.

Is it possible to have a look at the TikZ source? Do you use any GUI, or you code them up from scratch? Say, Figure 5.9, for example.

**Comment by mpd37** [comment]
- We prefer \mathbds{R} to \mathbb{R}
- \mathbb{I} would introduce some inconsistent notation. We may use \mathbb{A} to denote tensors if necessary
- \emptyset seems to be good to denote an empty set
- the gradient is a row vector and identical to the Jacobian
- We need to have a discussion about the differential operator (and some other operators). It's on the list!
- Thanks. I used ipe to generate this figure (and 5.7, 5.8). Need to figure out how to get italics + boldfont...
- I looked at the spacing, and it will be fixed with the next major update (maybe in 10 days?). Good  catch!

TikZ source for figure 5.9, see here:

[autodiff_example.txt](https://github.com/mml-book/mml-book.github.io/files/2006853/autodiff_example.txt)

**Comment by Atcold** [comment]
- Hmm, I think `\mathbds{}` is sorta ugly. I saw it being used only because authors didn't know about `\mathbb{}`. Are you saying you prefer it aesthetically speaking? I'm puzzled...
 - About the empty set, [I'm not the only one](https://tex.stackexchange.com/q/22798/33287) with this opinion.
 - Are you sure the gradient is a matrix's row? I think that all vectors, hence the gradient, are columns. That's why it's common to see the gradient defined as the transposition of the Jacobian over a scalar field.
 - Thanks, I didn't know about Ipe. I usually use Inkscape or even PowerPoint.
 - Thanks for the source code!

**Comment by mpd37** [comment]
- Yes, I prefer \mathds aesthetically speaking
- We will have a discussion about \emptyset vs \varnothing for the empty set
- There is no common agreement whether one should define the gradient as a row vector or a column vector, and this seems to be depending on the application. However, If you don't define the gradient as a row vector, the chain-rule will not work out and you will need to start transposing things. This will become really messy when you start working with tensors (e.g., derivatives of matrices w.r.t. vectors)

**Comment by Atcold** [comment]
For the derivative of the composite function I simply use the Jacobian.
The gradient, as far as I know, is defined only in scalar fields.
But again, as you say, maybe it's just application / field dependent.
Also, I haven't yet played with tensorial math, so, here I don't know, to be honest.

**Comment by mpd37** [comment]
We discussed you suggestions and decided on the notation. Thanks for raising this issue.
