### ISSUE TITLE
Associativity property of scalar-matrix multiplication

### ISSUE THREAD

**Issue by SantiDu** [mml-book/mml-book.github.io#420]
I'm confused about the associativity property of scalar-matrix multiplication in page 26, draft (2019-10-15), I don't understand why is  (λB)C = B(λC) an associative property, from my understanding, this is commutative law.
It will be great that someone could explain it.

**Comment by mpd37** [comment]
Agree: this should not be under "associativity". I will add a new bullet point just for this, but I'm a bit hesitant to call this "commutativity". While it is commutative w.r.t. the scalar, I believe people will be confused because it's not commutative w.r.t. the matrices. 

Here's what I have in mind:
![Screenshot from 2019-10-18 08-32-25](https://user-images.githubusercontent.com/5500569/67075229-ae127b00-f182-11e9-9f0d-c712c9105ece.png)

**Comment by SantiDu** [comment]
Thanks, I believe this is clearer than before.
