### ISSUE TITLE
1. Figure 2.13, page 62, Example 2.26 (Affine Subspaces)

### ISSUE THREAD

**Issue by vbartle** [mml-book/mml-book.github.io#531]
1. Figure 2.13, page 62, Example 2.26 (Affine Subspaces)
**Describe the mistake**
x_0 + lamba * u used in figure and figure description.
x_0 + lambda * x_1 used in example text

**Location**
Please provide the 
1. version (bottom of page) “Draft (2020-03-07) of “Mathematics for Machine Learning”. Feedback: https://mml-book.com. “
2. Chapter 2
3. page 62
4. line number/equation number, Figure 2.13

**Proposed solution**
A clear and concise description of what you would like to change.
Probably best to replace instances of ‘u’ in the figure and figure description with x_1. 

**Additional context**
I compared this with your original lecture notes (P116 of https://sml-group.cc/teaching/2015-16/mathematical-methods/notes.pdf) wherein you explain that y are points  along L. This isn’t stated in the MML book and I think it’s helpful for understanding the figure, because x_0 is called a support point, but the figure shows a quiver, and one would have to make that connection implicitly.

**Comment by mpd37** [comment]
Thanks for this. This is clearly and inconsistency. I'll replace the x_i in the example (and the figure) with b_i, so that it is more consistent with the text just before the example.

Regarding the caption of the figure. I'll change this to the following (which should make things clearer):
Lines are affine subspaces. Vectors $\vec{y}$ on a line $\vec x_0 + \lambda \vec b_1$ lie
  in an affine subspace $L$ with support point $\vec{x}_0$ and
  direction $\vec{b}_1$.
