### ISSUE TITLE
Make the LaTeX template available

### ISSUE THREAD

**Issue by Nathan-Furnal** [mml-book/mml-book.github.io#584]
Hi,

Would it be possible to make the LaTeX template of the book available ? Especially in a `.sty` form or something similar ?

Thanks!

**Comment by mpd37** [comment]
The template we use is a custom one made by Cambridge University Press, which we cannot share. However, we also do not recommend using it because it's extremely brittle. 
Most features (like the huge margins with text in them) you can get from a tufte-style latex template, which you can easily find online.

**Comment by Nathan-Furnal** [comment]
Alright thanks for the answer
