### ISSUE TITLE
Chapter 11 Feedback

### ISSUE THREAD

**Issue by adelejackson** [mml-book/mml-book.github.io#60]
This is a list of typos in Chapter 12, version as of 30/06/18.

L. 4958: such as the EM algorithm [and] a latent variable // (not sure what should go in the bracket, but there should be something)
L. 4983: can describe datasets with multiple “clusters”, ~~see~~ [such as in] Figure 12.1 ~~for an example of such a dataset.~~
Line numbering seems to be erratic through this chapter (stops and starts).
L. [unnumbered]: ~~Generally, a~~[A]ny [local] optimum of a function
L. 5011: I would highlight the remark following this more, if possible -- it's a very important point for getting any intuition for this
L. [unnumbered, after 5023]: can be interpreted ~~of~~ [as] a Monte-Carlo
L. 5028: or PCA in Section 11[,] cannot be
L. [unnumbered, after 5030]: To ~~proof~~ [prove] Theorem 12.2
L. [unnumbered, after 5030]: if it was possible to suppress numbering on the equation currently labelled 12.37, would be good as it's a piece of the equation that finishes on the next line
Eq. 12.48: personally, would drop the comma at the end of the line
L. 5039: As ~~for~~ [with] // I read "for" initially as saying "we will now deal with"
L. 5040: \Sigma_j, ~~j=1,\dots, K,~~ through
p. 298: having the set of update equations starting at the bottom of this page split over the image is awkward; force the image to come after them.
Fig 12.8, 12.9 seems like they should come in the opposite order, as they appear in the text in the opposite order.
L. 5094: this sampling procedure should link explicitly with ancestral sampling discussion (L. 5137)
L. 5107: data point x. [(]Note that... L5108: ...where k=1,\dots,K.[)]
L. 5118: this paragraph repeats the idea in L. 5106-08. Condense?
L. 5134: would be good to have section references here
L. 5186: would be good to mention issues with bin choices in histograms

Generally, I find it a little odd that the start of the proofs is "Proof<tab>" with no full stop (compare to "Remark.").

I've found students like the approach of thinking of finding mixture models from the ancestral sampling point of view -- that someone has followed the procedure of generating a latent variable value (a choice of k), then generated a point x using that, then discarded the latent variable, and we just have the samples that result. I'm not sure how you'd highlight that, but to me it appears very late in the chapter! I see the second half of this chapter (from the latent variable perspective onwards) as much more friendly to intuition than the first half.

**Comment by chengsoonong** [comment]
We have reorganised the book, Gaussian Mixture Models is now Chapter 11.

**Comment by mpd37** [comment]
Thanks for the great comments.

- I added a comment in the margin to visually highlight the remark on the relationship between likelihood and responsibilities.
- L. 5040: \Sigma_j, j=1,\dots, K, through --- I wanted to leave this in to make it very explicit.
- We will continue fixing the formatting so that things actually look nice in the end. 
- added a note that the sampling procedure is called ancestral sampling and also made it more explicit, i.e., we sample z_i from p(z) and then x_i from p(x|z_i)
- L. 5118: Decided not to condense. Effectively there's one sentence that is somewhat redundant, but this is the right place to have. And I wouldn't want to delete it from the previous paragraph.
- I expanded a bit on the ancestral sampling remark. Here's what it looks like now. 
![image](https://user-images.githubusercontent.com/5500569/42308974-3e8bf4a2-802f-11e8-8963-f804639d0403.png)
It would be great to have your opinion on this.
