### ISSUE TITLE
wording on page 128

### ISSUE THREAD

**Issue by sophoi** [mml-book/mml-book.github.io#650]
**Describe the mistake**
A phrase on page 128 needs minor editing, so the reader can easily understand it.
 
**Location**
Please provide the 
1. version: online PDF Draft (2021-01-14)
2. Chapter 4
3. page 128
4. in the last paragraph of the gray box, the phrase after the dash:
... so a science fiction lover v1 gives a rating of zero to everything
but science fiction themed – this logic is implied the diagonal substructure
for the singular value matrix Σ.

**Proposed solution**
Change it to (add "in" and change "for" to "of"):
– this logic is implied **in** the diagonal substructure **of** the singular value matrix Σ.

**Additional context**
When I first read this part, I had to read it several times to guess the meaning of it

**Comment by mpd37** [comment]
Thanks for catching this. I added the word "by", so that it reads now

An idealized science fiction lover is a purist and only loves science fiction movies, so a science fiction lover v1 gives a rating of zero to everything but science fiction themed---this logic is implied by the  diagonal substructure for  the singular value matrix Sigma.
