### ISSUE TITLE
A few minor typos (Chapter 2 and Chapter 5)

### ISSUE THREAD

**Issue by mdpedersen** [mml-book/mml-book.github.io#69]
Chapter 2 (Linear Algebra, version 2018-07-25):

- Page 55, line 2 of continued example: there seems to be a footnote reference (2) which I can't find anywhere.
- 1359: "We call V and W also..." -> "We also call V and W..."
- 1366: "It always holds that $\phi( {0_V} ) = 0_W$", I guess strictly speaking should be $\phi( {0_V} ) = {0_W}$.
- 1428: "The vector a is called translation vector" -> "The vector a is called the translation vector".

Chapter 5 (Vector Calculus, version 2018-07-02):

1. Page 141 (Def. 5.4): Perhaps this is standard, but seems a bit strange to (paraphrased) "define the tailor series as f(x) = T_\infty(x)"; and then just in the next few sentences consider a special case (analytical functions) where actually f(x) = T_\infty(x). 
2. Page 143 (Eq. 5.30): Following on from the above comment, maybe this should be T_\infty = ... instead of f(x) = ... (we don't at this point know that f is analytical).
3. Page 144 (Eq 5.40): $(\circ f)^\prime(x)$ should be $(g^\prime \circ f)^\prime(x)$ (missing g).
4. 2704: "we used the compact vector notation" - did we, given that actually we defined a row vector?
5. 2736: "makes only sense" -> "only makes sense".
6. Page 150 (Eq. 5.72): "we identify the desired basis change matrix as": is this not the transformation matrix (w.r.t. the standard basis) rather than a basis change matrix? It seems to me that the description under Approach 2 generally confuses the two notions; but I might just be misunderstanding something here.
7. Page 153: Side note seems to have gone wrong.
8. Page 153 (Eq 5.93): Notation is a bit confusing; perhaps it would help if you are explicit and say "Element d is given by..." instead of "Every element is given by...".
9. Page 153 (Last sentence of Ex. 5.10): "If consider deep" -> "If considering deep".
10. Page 155 (Eq. 5.98): "f \in R^M" -> "f(x) \in R^M".
11. Page 157 (Eq. 5.114): Should the "tr" function be defined anywhere?
12. Page 158, second-last line: "for j = 0...K-1" - seems that this should be "for j = 1...K" (because f_i here is parameterised by A_i, b_i). But then, in the following example, f_i is parameterised by A_{i-1}, b_{i-1}, which seems a bit inconsistent.
13. 2883: "computing graph" -> "computation graph".
14. 2907 and 2909: These look identical (one should have dx and dy swapped presumably).
15. Page 166 (Eq.  5.17): as previously, I'm not sure if tr is defined at this point.
16. 2932: "integral generally not be solved" -> "integral generally cannot be solved".

**Comment by mpd37** [comment]
- Chapter 2: I removed the set brackets from all 0-vectors. They make only limited sense and are not very instructive since those sets only contain a single element...

Chapter 5:

Everything not mentioned below is fixed.

1. I removed the f(x) = ... from the definition of the Taylor series. It should not belong there.
4. The compact vector notation refers to x = [x_1, ..., x_n]^T, not to the gradient. I reformulated this to "... where we defined the column vector x =[x_1, .., x_n]^T
6. The basis change matrix is a transformation matrix that maps one set of basis vectors onto the other basis vectors (this is how you find it). But then this transformation matrix also represents coordinates w.r.t. basis 1 as coordinates w.r.t. 2. So, it's both: a basis change matrix and a transformation matrix. (this is for Approach 1)
7. We don't know how to fix this at the moment. We'll keep working on it.
10. We chose f not so much as a function but more as a variable (similar to y = ax + b). And given that we take derivatives w.r.t. A, we would need to make this also explicit in f and call it f(A, x) or f(A) alone. This, we find more confusing.
