### ISSUE TITLE
Weird Python code in sidebar

### ISSUE THREAD

**Issue by divilian** [mml-book/mml-book.github.io#748]
**Describe the mistake**
In the sidebar of p.22, there's some random-looking Python code in green at the bottom.

**Location**
1. 2023-02-15
2. 2
3. 22
4. sidebar

**Comment by saad-24** [comment]
What actually is the issue with that python code?

**Comment by divilian** [comment]
> What actually is the issue with that python code?

I guess my first question is simply: "what is a random snippet of Python code doing here?" This isn't a book that includes any programming/implementation content. Afaik, there are zero other references to code in Python or any other programming language anywhere in the book. Why Python specifically, and why this isolated example?

**Comment by mpd37** [comment]
there are a few isolated examples in the book. we thought it may help some people when it comes to thinking about how to implement it.  we chose python (ish) because it's quite compact and most people will have had some exposure to it before. however, it's not critical to understand (if one doesn't have any coding experience)
